// Package vmnet installs the packaged macOS network helper using Lima's model.
//
// Native VZ guests do not enter this package. QEMU preflight and start call
// [Setup.Ensure]; an already valid installation requires no prompt or writes.
// A missing helper or outdated sudoers file requires an interactive confirmation
// followed by sudo's administrator authentication.
// The configured group is preserved, including an existing everyone group;
// new network configurations use the defaults from the pinned Lima dependency.
// Checks execute an installed helper's --version as the regular user to detect
// host incompatibility without creating a network. Setup errors retain the
// reason installation is required, including in a noninteractive terminal.
//
//	QEMU operation → Lima network checks → ready
//	                       ↓ missing setup
//	                 user confirmation
//	                       ↓
//	             sudo limanix vmnet-install
//	                       ↓
//	     embedded helper → /opt/socket_vmnet/bin/socket_vmnet
//	     Lima Sudoers()  → /private/etc/sudoers.d/lima
//
// [Install] is the short-lived privileged boundary. It accepts a configuration
// snapshot, restricts write destinations, verifies root-owned paths, and installs
// bytes from its own embedded bundle. It never runs an extracted helper from a
// user-writable location. Sudoers are generated by Lima, checked by visudo and
// published atomically; an existing file is backed up before replacement.
//
// Lima retains ownership of network configuration, daemon lifecycle, socket/PID
// paths and command authorization. This package does not install QEMU, rewrite
// networks.yaml, start a launchd service or grant sudo access to Limanix itself.
// Read setup.go for the unprivileged flow and install.go for privileged writes.
package vmnet
